-- Dati iniziali: i 12 modelli del prototipo (da src/lib/models.ts).

insert into public.models (id, position, name, age, gender, city, categories, tags, bio, rating, reviews, sales, palette) values
  ('giulia-r', 1, 'Giulia R.', 26, 'donna', 'Milano', array['Moda', 'Beauty']::text[], array['capelli rossi', 'lentiggini', 'occhi verdi']::text[], 'Modella moda e beauty con 6 anni di esperienza su campagne internazionali. Volto naturale, perfetto per skincare e campagne editoriali.', 4.9, 128, 312, array['#f97316', '#be123c']::text[]),
  ('marco-b', 2, 'Marco B.', 32, 'uomo', 'Roma', array['Fitness', 'Commercial']::text[], array['atletico', 'barba', 'tatuaggi']::text[], 'Personal trainer e modello fitness. Fisico atletico, ideale per sportswear, integratori e brand outdoor.', 4.8, 94, 201, array['#0ea5e9', '#1e3a8a']::text[]),
  ('aisha-k', 3, 'Aisha K.', 24, 'donna', 'Torino', array['Moda', 'Editoriale']::text[], array['capelli ricci', 'alta', 'pelle scura']::text[], 'Volto editoriale per riviste di moda. Grande versatilità espressiva, dal look minimal all''haute couture.', 5, 76, 188, array['#a855f7', '#4c1d95']::text[]),
  ('luca-m', 4, 'Luca M.', 45, 'uomo', 'Napoli', array['Commercial', 'Cinema']::text[], array['brizzolato', 'sorriso', 'papà']::text[], 'Attore e modello commercial. Il volto rassicurante per banche, assicurazioni e food.', 4.7, 63, 140, array['#64748b', '#0f172a']::text[]),
  ('sofia-l', 5, 'Sofia L.', 21, 'donna', 'Firenze', array['Lifestyle', 'Beauty']::text[], array['bionda', 'gen z', 'sorriso']::text[], 'Content creator e modella lifestyle. Perfetta per brand rivolti a un pubblico giovane.', 4.9, 151, 420, array['#facc15', '#ea580c']::text[]),
  ('kenji-t', 6, 'Kenji T.', 29, 'uomo', 'Milano', array['Moda', 'Editoriale']::text[], array['capelli lunghi', 'minimal', 'streetwear']::text[], 'Modello moda specializzato in streetwear e campagne concettuali.', 4.8, 58, 97, array['#10b981', '#064e3b']::text[]),
  ('elena-v', 7, 'Elena V.', 63, 'donna', 'Bologna', array['Senior', 'Commercial']::text[], array['capelli bianchi', 'elegante', 'nonna']::text[], 'Modella senior per campagne pharma, travel e lifestyle. Eleganza senza tempo.', 5, 41, 85, array['#e11d48', '#881337']::text[]),
  ('alex-p', 8, 'Alex P.', 27, 'non-binario', 'Milano', array['Moda', 'Beauty', 'Editoriale']::text[], array['androgino', 'rasato', 'piercing']::text[], 'Volto androgino per moda, beauty e campagne inclusive.', 4.9, 70, 133, array['#ec4899', '#6d28d9']::text[]),
  ('davide-c', 9, 'Davide C.', 38, 'uomo', 'Bari', array['Lifestyle', 'Commercial']::text[], array['mediterraneo', 'barba', 'business']::text[], 'Modello lifestyle e corporate. Ideale per tech, automotive e finance.', 4.6, 52, 110, array['#f59e0b', '#78350f']::text[]),
  ('chiara-n', 10, 'Chiara N.', 30, 'donna', 'Roma', array['Fitness', 'Lifestyle']::text[], array['yoga', 'mora', 'atletica']::text[], 'Istruttrice di yoga e modella fitness per brand wellness e activewear.', 4.8, 88, 176, array['#14b8a6', '#155e75']::text[]),
  ('omar-s', 11, 'Omar S.', 23, 'uomo', 'Genova', array['Moda', 'Lifestyle']::text[], array['capelli ricci', 'gen z', 'streetwear']::text[], 'Giovane modello per brand urban, sneakers e musica.', 4.7, 39, 74, array['#6366f1', '#1e1b4b']::text[]),
  ('francesca-d', 12, 'Francesca D.', 35, 'donna', 'Verona', array['Cinema', 'Commercial']::text[], array['mamma', 'castana', 'naturale']::text[], 'Attrice e modella commercial, volto ideale per famiglia, casa e food.', 4.9, 67, 152, array['#84cc16', '#365314']::text[]);

insert into public.licenses (model_id, tier, name, price, duration_months, territory, usages, generations) values
  ('giulia-r', 'base', 'Base', 180, 6, 'Italia', array['Social media organici', 'Contenuti web']::text[], 'Fino a 50 immagini AI'),
  ('giulia-r', 'standard', 'Standard', 450, 12, 'Europa', array['Social media e ads', 'E-commerce', 'Newsletter']::text[], 'Fino a 500 immagini AI + 10 video'),
  ('giulia-r', 'premium', 'Premium', 1080, 24, 'Mondo', array['Campagne ADV', 'TV e cinema', 'Out of home', 'E-commerce']::text[], 'Immagini e video illimitati'),
  ('marco-b', 'base', 'Base', 150, 6, 'Italia', array['Social media organici', 'Contenuti web']::text[], 'Fino a 50 immagini AI'),
  ('marco-b', 'standard', 'Standard', 375, 12, 'Europa', array['Social media e ads', 'E-commerce', 'Newsletter']::text[], 'Fino a 500 immagini AI + 10 video'),
  ('marco-b', 'premium', 'Premium', 900, 24, 'Mondo', array['Campagne ADV', 'TV e cinema', 'Out of home', 'E-commerce']::text[], 'Immagini e video illimitati'),
  ('aisha-k', 'base', 'Base', 220, 6, 'Italia', array['Social media organici', 'Contenuti web']::text[], 'Fino a 50 immagini AI'),
  ('aisha-k', 'standard', 'Standard', 550, 12, 'Europa', array['Social media e ads', 'E-commerce', 'Newsletter']::text[], 'Fino a 500 immagini AI + 10 video'),
  ('aisha-k', 'premium', 'Premium', 1320, 24, 'Mondo', array['Campagne ADV', 'TV e cinema', 'Out of home', 'E-commerce']::text[], 'Immagini e video illimitati'),
  ('luca-m', 'base', 'Base', 130, 6, 'Italia', array['Social media organici', 'Contenuti web']::text[], 'Fino a 50 immagini AI'),
  ('luca-m', 'standard', 'Standard', 325, 12, 'Europa', array['Social media e ads', 'E-commerce', 'Newsletter']::text[], 'Fino a 500 immagini AI + 10 video'),
  ('luca-m', 'premium', 'Premium', 780, 24, 'Mondo', array['Campagne ADV', 'TV e cinema', 'Out of home', 'E-commerce']::text[], 'Immagini e video illimitati'),
  ('sofia-l', 'base', 'Base', 120, 6, 'Italia', array['Social media organici', 'Contenuti web']::text[], 'Fino a 50 immagini AI'),
  ('sofia-l', 'standard', 'Standard', 300, 12, 'Europa', array['Social media e ads', 'E-commerce', 'Newsletter']::text[], 'Fino a 500 immagini AI + 10 video'),
  ('sofia-l', 'premium', 'Premium', 720, 24, 'Mondo', array['Campagne ADV', 'TV e cinema', 'Out of home', 'E-commerce']::text[], 'Immagini e video illimitati'),
  ('kenji-t', 'base', 'Base', 170, 6, 'Italia', array['Social media organici', 'Contenuti web']::text[], 'Fino a 50 immagini AI'),
  ('kenji-t', 'standard', 'Standard', 425, 12, 'Europa', array['Social media e ads', 'E-commerce', 'Newsletter']::text[], 'Fino a 500 immagini AI + 10 video'),
  ('kenji-t', 'premium', 'Premium', 1020, 24, 'Mondo', array['Campagne ADV', 'TV e cinema', 'Out of home', 'E-commerce']::text[], 'Immagini e video illimitati'),
  ('elena-v', 'base', 'Base', 140, 6, 'Italia', array['Social media organici', 'Contenuti web']::text[], 'Fino a 50 immagini AI'),
  ('elena-v', 'standard', 'Standard', 350, 12, 'Europa', array['Social media e ads', 'E-commerce', 'Newsletter']::text[], 'Fino a 500 immagini AI + 10 video'),
  ('elena-v', 'premium', 'Premium', 840, 24, 'Mondo', array['Campagne ADV', 'TV e cinema', 'Out of home', 'E-commerce']::text[], 'Immagini e video illimitati'),
  ('alex-p', 'base', 'Base', 190, 6, 'Italia', array['Social media organici', 'Contenuti web']::text[], 'Fino a 50 immagini AI'),
  ('alex-p', 'standard', 'Standard', 475, 12, 'Europa', array['Social media e ads', 'E-commerce', 'Newsletter']::text[], 'Fino a 500 immagini AI + 10 video'),
  ('alex-p', 'premium', 'Premium', 1140, 24, 'Mondo', array['Campagne ADV', 'TV e cinema', 'Out of home', 'E-commerce']::text[], 'Immagini e video illimitati'),
  ('davide-c', 'base', 'Base', 110, 6, 'Italia', array['Social media organici', 'Contenuti web']::text[], 'Fino a 50 immagini AI'),
  ('davide-c', 'standard', 'Standard', 275, 12, 'Europa', array['Social media e ads', 'E-commerce', 'Newsletter']::text[], 'Fino a 500 immagini AI + 10 video'),
  ('davide-c', 'premium', 'Premium', 660, 24, 'Mondo', array['Campagne ADV', 'TV e cinema', 'Out of home', 'E-commerce']::text[], 'Immagini e video illimitati'),
  ('chiara-n', 'base', 'Base', 140, 6, 'Italia', array['Social media organici', 'Contenuti web']::text[], 'Fino a 50 immagini AI'),
  ('chiara-n', 'standard', 'Standard', 350, 12, 'Europa', array['Social media e ads', 'E-commerce', 'Newsletter']::text[], 'Fino a 500 immagini AI + 10 video'),
  ('chiara-n', 'premium', 'Premium', 840, 24, 'Mondo', array['Campagne ADV', 'TV e cinema', 'Out of home', 'E-commerce']::text[], 'Immagini e video illimitati'),
  ('omar-s', 'base', 'Base', 100, 6, 'Italia', array['Social media organici', 'Contenuti web']::text[], 'Fino a 50 immagini AI'),
  ('omar-s', 'standard', 'Standard', 250, 12, 'Europa', array['Social media e ads', 'E-commerce', 'Newsletter']::text[], 'Fino a 500 immagini AI + 10 video'),
  ('omar-s', 'premium', 'Premium', 600, 24, 'Mondo', array['Campagne ADV', 'TV e cinema', 'Out of home', 'E-commerce']::text[], 'Immagini e video illimitati'),
  ('francesca-d', 'base', 'Base', 130, 6, 'Italia', array['Social media organici', 'Contenuti web']::text[], 'Fino a 50 immagini AI'),
  ('francesca-d', 'standard', 'Standard', 325, 12, 'Europa', array['Social media e ads', 'E-commerce', 'Newsletter']::text[], 'Fino a 500 immagini AI + 10 video'),
  ('francesca-d', 'premium', 'Premium', 780, 24, 'Mondo', array['Campagne ADV', 'TV e cinema', 'Out of home', 'E-commerce']::text[], 'Immagini e video illimitati');
